version: '3.8'

services:
  app:
    image: chaewon012/laundreader:latest
    container_name: user-api
    ports:
      - "8080:8080"
    env_file:
      - ./secure-submodule/env/compose-prod.env
    restart: always
    networks:
      - laundreader

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - laundreader

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - laundreader

networks:
  laundreader:
    driver: bridge

volumes:
  grafana_data: